const events = [
  {
    _id: '1',
    name: 'Douga explore',
    image: '/eventImages/douga.jpg',
    eventDate: '20/06/2022',
    duration: '5 jours',
    places: 9,
    price: 280,
    capacity: 50,
    numberOfPlacesLeft: 6,
    organizer: 'Eventura',
    categorie: 'Archiologie',
    niveauMin: 3,
  },
  {
    _id: '2',
    name: 'Port Punique',
    image: '/eventImages/punicport.jpg',
    eventDate: '6/07/2022',
    duration: '1 jour',
    places: 3,
    price: 80,
    capacity: 30,
    numberOfPlacesLeft: 19,
    organizer: 'Mitux',
    categorie: 'Archiologie',
    niveauMin: 3,
  },
  {
    _id: '3',
    name: 'Douz',
    image: '/eventImages/douz.jpg',
    eventDate: '12/08/2022',
    duration: '7 jours',
    places: 9,
    price: 160,
    capacity: 30,
    numberOfPlacesLeft: 11,
    organizer: 'Eventura',
    categorie: 'Exploration',
    niveauMin: 1,
  },
  {
    _id: '4',
    name: 'Douz',
    image: '/eventImages/douz.jpg',
    eventDate: '12/08/2022',
    duration: '7 jours',
    places: 9,
    price: 160,
    capacity: 30,
    numberOfPlacesLeft: 11,
    organizer: 'Eventura',
    categorie: 'Exploration',
    niveauMin: 1,
  },
  {
    _id: '5',
    name: 'Port Punique',
    image: '/eventImages/punicport.jpg',
    eventDate: '6/07/2022',
    duration: '1 jour',
    places: 3,
    price: 80,
    capacity: 30,
    numberOfPlacesLeft: 19,
    organizer: 'Mitux',
    categorie: 'Archiologie',
    niveauMin: 3,
  },
  {
    _id: '6',
    name: 'Douga explore',
    image: '/eventImages/douga.jpg',
    eventDate: '20/06/2022',
    duration: '5 jours',
    places: 9,
    price: 280,
    capacity: 50,
    numberOfPlacesLeft: 0,
    organizer: 'Eventura',
    categorie: 'Archiologie',
    niveauMin: 3,
  },
]

export default events
